server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:5432}/${DATASOURCE_DB_NAME:postgres}?prepareThreshold=0
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}


  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true


jwt:
  secret: 'my_secret_key_which_should_be_very_long'
  expiration: 86400000  # 24 hours in milliseconds
